version: '3'
services:
  # products-api:
  #   container_name: products-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5000:5000'
  #   expose:
  #     - '5000'
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
